plugins:
  mumble_enabled:
    default: false
    client: false
  mumble_interval:
    default: 60000
    client: true
  mumble_cvp:
    default: ''
  mumble_show_empty_channels:
    default: false
    client: false
